# Generated by Django 5.2.1 on 2025-06-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='Username',
        ),
    ]
